auth:
  type: LOGIN_FORM

spring:
  security:
    user:
      name: admin
      password: admin

kafka:
  clusters:
    - bootstrapServers: broker-1:19092,broker-2:19092,broker-3:19092,
      name: local


