CREATE TABLE google_login (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  given_name VARCHAR(255),
  family_name VARCHAR(255),
  picture TEXT,
  access_token VARCHAR(255) NOT NULL,
  issued_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  expired_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  FOREIGN KEY (email) REFERENCES users(email) ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE TRIGGER "google_login_updated_at" BEFORE
INSERT
  OR
UPDATE ON "public"."google_login" FOR EACH ROW EXECUTE FUNCTION updated_at_autocomplete();