version: '3.3'
services:
  db:
    container_name: postgres
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      # POSTGRES_DB: iot_backend // init in sql script
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

# You can uncomment and configure volumes if you need persistent storage
# volumes:
#   pg-data:
#     driver: local
