// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: locale.sql

package db

import (
	"context"
)

const getAllLocales = `-- name: GetAllLocales :many
select language, raw_message,translated_message
from locale
`

type GetAllLocalesRow struct {
	Language          string
	RawMessage        string
	TranslatedMessage string
}

func (q *Queries) GetAllLocales(ctx context.Context) ([]GetAllLocalesRow, error) {
	rows, err := q.db.Query(ctx, getAllLocales)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllLocalesRow
	for rows.Next() {
		var i GetAllLocalesRow
		if err := rows.Scan(&i.Language, &i.RawMessage, &i.TranslatedMessage); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
