// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AUser struct {
	ID        int32
	Username  string
	Email     string
	Password  string
	Role      string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type GoogleLogin struct {
	ID          uuid.UUID
	Email       string
	Name        string
	GivenName   pgtype.Text
	FamilyName  pgtype.Text
	Picture     pgtype.Text
	AccessToken string
	IssuedAt    pgtype.Timestamp
	ExpiredAt   pgtype.Timestamp
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type Test struct {
	ID        int32
	Name      string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	StartedAt pgtype.Timestamp
	Balance   pgtype.Numeric
}

type User struct {
	ID        uuid.UUID
	Username  string
	Email     string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
