// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type EmailWhitelist struct {
	ID        int32
	Email     string
	CreatedAt pgtype.Timestamp
}

type GoogleLogin struct {
	ID          int32
	Username    string
	Email       string
	AccessToken string
	IssuedAt    pgtype.Timestamp
	ExpiredAt   pgtype.Timestamp
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type Locale struct {
	ID                int32
	Language          string
	RawMessage        string
	TranslatedMessage string
	CreatedAt         pgtype.Timestamp
	UpdatedAt         pgtype.Timestamp
}

type PasswordLogin struct {
	ID        int32
	Email     string
	Password  string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Project struct {
	ID          int32
	ProjectName string
	Comment     pgtype.Text
	Creator     int32
	Status      pgtype.Text
	Address     pgtype.Text
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type Sketch struct {
	ID           int32
	ProjectName  string
	Comment      pgtype.Text
	ProjectID    int32
	UploaderID   int32
	ThumbnailUrl pgtype.Text
	FullImageUrl string
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}

type Test struct {
	ID        int32
	Name      string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	StartedAt pgtype.Timestamp
	Balance   pgtype.Numeric
}

type User struct {
	ID        int32
	Username  string
	Email     string
	Info      []byte
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
