// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
)

type Querier interface {
	CreateNewUser(ctx context.Context, arg CreateNewUserParams) error
	GetAllLocales(ctx context.Context) ([]GetAllLocalesRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GoogleLogin(ctx context.Context, arg GoogleLoginParams) error
	GoogleLoginUpdateUser(ctx context.Context, arg GoogleLoginUpdateUserParams) error
	InitPasswordLogins(ctx context.Context, digest string) error
	InitUsers(ctx context.Context) error
	VerifyUserCredentials(ctx context.Context, arg VerifyUserCredentialsParams) (bool, error)
}

var _ Querier = (*Queries)(nil)
